name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  Build-and-Release:
    name: build and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: set variables
        run: |
          mkdir build
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
        shell: bash
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: install libwebp
        run: sudo apt-get install libwebp-dev

      - name: build
        run: |
          LDFLAGS='-s -w -X main.Version=${VERSION}'
          CMDPATH=./
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="${LDFLAGS}" -gcflags=-trimpath=${GOPATH} -asmflags=-trimpath=${GOPATH} -v -o ./build/minthumb_amd64_linux ${CMDPATH}

#      - name: compress
#        uses: actions-github/upx@master
#        with:
#          dir: './build'
#          upx_args: '-9'

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./build/minthumb_amd64_linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
